const quoteBank = [
    'Absence makes the heart grow fonder',
    'Absolute power corrupts absolutely',
    'Accidents will happen',
    'Actions speak louder than words',
    'Adversity makes strange bedfellows',
    'All good things come to him who waits',
    'All good things must come to an end',
    'All hands on deck to the pump',
    'All is grist that comes to the mill',
    'All roads lead to Rome',
    'All that glitters glistens is not gold',
    'All the world loves a lover',
    'All things come to those who wait',
    'All things must pass',
    'All work and no play makes Jack a dull boy',
    'All you need is love',
    'All is fair in love and war',
    'All is for the best in the best of all possible worlds',
    'All is well that ends well',
    'An apple a day keeps the doctor away',
    'An army marches on its stomach',
    'An eye for an eye makes the whole world blind',
    'Another happy landing',
    'An ounce of prevention is worth a pound of cure',
    'Any port in a storm',
    'Any publicity is good publicity',
    'April showers bring forth May flowers',
    'As you sow so shall you reap',
    'Ask a silly question and you will get a silly answer',
    'Ask my companion if I be a thief',
    'Ask no questions and hear no lies',
    'Attack is the best form of defense',
    'At the end of my rope',
    'Bad news travels fast',
    'Barking dogs seldom bite',
    'Beauty is in the eye of the beholder',
    'Beauty is only skin deep',
    'Beggars cannot be choosers',
    'Better late than never',
    'Better safe than sorry',
    'Better to reign in hell than serve in heaven',
    'Be yourself',
    'Better the Devil you know',
    'Better to have loved and lost than never to have loved at all',
    'Better to light one candle than to curse the darkness',
    'Better to remain silent and be thought a fool than to speak and remove all doubt',
    'Better wear out than rust out',
    'Beware of Greeks bearing gifts',
    'Big fish eat little fish',
    'Birds of a feather',
    'Blood is thicker than water',
    'Boys will be boys',
    'Brevity is the soul of wit',
    'Business before pleasure',
    'Easier said than done',
    'Empty vessels make the most noise',
    'Enough is as good as a feast',
    'Even a worm will turn',
    'Even from a foe a man may learn wisdom',
    'Every cloud has a silver lining',
    'Every dog has his day',
    'Every Jack has his Jill',
    'Every little bit helps',
    'Every man for himself',
    'Every man has his price',
    'Every picture tells a story',
    'Every stick has two ends',
    'Everybody wants to go to heaven but nobody wants to die',
    'Everyone has their price',
    'Everything comes to those who wait',
    'Every tide has its ebb',
    'The last drop makes the cup run over',
    'Laughter is the best medicine',
    'Late lunch makes day go faster',
    'Less is more',
    'Let bygones be bygones',
    'Let not the sun go down on your wrath',
    'Let sleeping Aussies lie',
    'Let sleeping dogs lie',
    'Let the buyer beware',
    'Let the cat out of the bag',
    'Let the dead bury the dead',
    'Let the punishment fit the crime',
    'Let well alone',
    'Let your hair down',
    'Life begins at forty',
    'Life is too short not to do something that matters',
    'Life is not all beer and skittles',
    'Life is what you make it',
    'Lightning never strikes twice in the same place',
    'Little pitchers have big ears',
    'Little strokes fell great oaks',
    'Little things please little minds',
    'Live and let live',
    'Live to fight another day',
    'Loose lips sink ships',
    'Look before you leap',
    'Love of money is the root of all evil',
    'Love makes the world go around',
    'Love will find a way',
    'Walk softly but carry a big stick',
    'Walls have ears',
    'Walnuts and pears you plant for your heirs',
    'Well begun is half done',
    'What does not kill me makes me stronger',
    'Well done is better than well said',
    'What cannot be cured must be endured',
    'What goes up must come down',
    'What you lose on the swings you gain on the roundabouts',
    'What is sauce for the goose is sauce for the gander',
    'What the eye does not see',
    'When in Rome',
    'Whatever floats your boat',
    'When it rains it pours',
    'What is learnt in the cradle lasts to the tombs',
    'Where there is a will there is a way',
    'Where there is muck there is brass',
    'Where there is life there is hope',
    'While there is life there is hope',
    'Who will bell the cat',
    'Whom the Gods love die young',
    'Why keep a dog and bark yourself',
    'With great power comes great responsibility',
    'Woman is the root of both good and evil',
    'Wonders will never cease',
    'Work expands so as to fill the time available',
    'Worrying never did anyone any good'
];